language: none

integrations:
  notifications:
    - integrationName: Amido Slack (#chatbots)
      type: slack
      recipients: "#chatbots"
      on_success: change
      on_failure: change
      on_pull_request: always

resources:
  - name: cb170_infra_master
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: RichardSlater/chatbot-170-infrastructure
      branch: master

  - name: azure_cli_config
    type: cliConfig
    integration: Azure (Chatbot Experiments)

  - name: schedule_2230
    type: time
    versionTemplate:
      interval: "30 22 * * *"

jobs:
  - name: provisioning
    type: runSh
    steps:
      - IN: azure_cli_config
      - IN: cb170_infra_master
      - TASK:
        - script: chmod +x $CB170_INFRA_MASTER_STATE/scripts/*.sh
        - script: $CB170_INFRA_MASTER_STATE/scripts/ensure-terraform.sh 0.11.5
        - script: . $CB170_INFRA_MASTER_STATE/scripts/export-azure-environment.sh
        - script: $CB170_INFRA_MASTER_STATE/scripts/execute-terraform.sh apply

  - name: deprovisioning
    type: runSh
    steps:
      - IN: azure_cli_config
      - IN: schedule_2230
      - IN: cb170_infra_master
        switch: off
      - IN: provisioning
        switch: off
      - TASK:
        - script: chmod +x $CB170_INFRA_MASTER_STATE/scripts/*.sh
        - script: $CB170_INFRA_MASTER_STATE/scripts/ensure-terraform.sh 0.11.5
        - script: . $CB170_INFRA_MASTER_STATE/scripts/export-azure-environment.sh
        - script: $CB170_INFRA_MASTER_STATE/scripts/execute-terraform.sh destroy
