language: none

resources:

  - name: github_cb170_infra_master
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: RichardSlater/chatbot-170-infrastructure
      branch: master

  - name: azure_cli_config
    type: cliConfig
    integration: Azure (Chatbot Experiments)

  - name: schedule_2230
    type: time
    versionTemplate:
      interval: "30 22 * * *"

jobs:
  - name: provisioning
    type: runSh
    steps:
      - IN: azure_cli_config
      - IN: github_cb170_infra_master
      - TASK:
        - script: chmod +x $GITHUB_CB170_INFRA_MASTER_STATE/scripts/*.sh
        - script: $GITHUB_CB170_INFRA_MASTER_STATE/scripts/ensure-terraform.sh 0.11.5
        - script: . $GITHUB_CB170_INFRA_MASTER_STATE/scripts/export-azure-environment.sh
        - script: $GITHUB_CB170_INFRA_MASTER_STATE/scripts/execute-terraform.sh apply

  - name: deprovisioning
    type: runSh
    steps:
      - IN: azure_cli_config
      - IN: schedule_2230
      - IN: github_cb170_infra_master
        switch: off
      - IN: provisioning
        switch: off
      - TASK:
        - script: chmod +x $GITHUB_CB170_INFRA_MASTER_STATE/scripts/*.sh
        - script: $GITHUB_CB170_INFRA_MASTER_STATE/scripts/ensure-terraform.sh 0.11.5
        - script: . $GITHUB_CB170_INFRA_MASTER_STATE/scripts/export-azure-environment.sh
        - script: $GITHUB_CB170_INFRA_MASTER_STATE/scripts/execute-terraform.sh destroy
